language: go
go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
install:
  - go get -t ./...
before_script:
  - sudo cat /etc/postgresql/9.5/main/pg_hba.conf
  - sudo cat /etc/postgresql/10/main/pg_hba.conf
  - sudo ss -ntlp
  - cd /
  - sudo -u postgres psql -c '\l' -c '\du'
  - sudo -u postgres psql -c "ALTER USER travis WITH PASSWORD '123456'"
  - cd -
script:
  - |
    if [[ $(go version) == *1.11* ]]; then
      go test -v -p 1 -covermode=count -coverprofile=coverage.out ./...
      go get github.com/mattn/goveralls
      $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    else
      go test -v -p 1 ./...
    fi
notifications:
  email:
    applejava@qq.com

