language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
    - PGPORT=5433

services:
  - postgresql

install:
  - go get -t ./...

before_script:
  - sudo -u postgres psql -c "ALTER USER travis WITH PASSWORD '123456'"

script:
  - |
    if [[ $(go version) == *1.11* ]]; then
      go test -v -covermode=count -coverprofile=coverage.out . ./...
      go get github.com/mattn/goveralls
      $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    else
      go test -v . ./...
    fi
notifications:
  email:
    applejava@qq.com

