language: go
go:
  - "1.10"
  - "1.16"
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
install:
  - go get -t ./...
script:
  - |
    if [[ $(go version) == *1.11* ]]; then
      set -e
      go test -v -p 1 -covermode=count -coverprofile=coverage.out ./...
      go get github.com/mattn/goveralls
      $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    else
      go test -v -p 1 ./...
    fi
notifications:
  email:
    applejava@qq.com

