language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
    - PGPORT=5433

services:
  - postgresql

install:
  - go get -t ./...
  - go get github.com/mattn/goveralls

before_script:
  - sudo -u postgres psql -c "ALTER USER travis WITH PASSWORD '123456'"

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci