language: go
go:
  - "1.8"
  - "1.9"
  - "1.10"
services:
  - postgresql
install:
  - go get -t ./...
before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres
  - psql -c 'CREATE USER develop;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE test TO develop;' -U postgres
script:
  - $GOPATH/bin/goveralls -service=travis-ci